### ISSUE TITLE
Create footer component

### ISSUE THREAD

**Issue by WinterBoii** [WinterBoii/JkpgCity-Project#15]
![Image](https://github.com/WinterBoii/JkpgCity-Project/assets/72822518/bc198625-9767-44e4-8954-821f96723993)

**Comment by Sky-De** [comment]
@WinterBoii hi, please assign this to me
Thanks

**Comment by WinterBoii** [comment]
Sorry can't, this is for study only

> @WinterBoii hi, please assign this to me Thanks
